name: surf_practice_chat_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  surf_study_jam: ^0.2.0

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  freezed: ^2.1.0+1
  bloc_concurrency: ^0.2.0
  flutter_secure_storage: ^5.1.0
  geolocator: ^9.0.1
  url_launcher: ^6.1.5
  permission_handler: ^10.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  freezed_annotation: ^2.1.0
flutter:

  uses-material-design: true
